[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --verbose --browser chromium
env =
    FLASK_ENV=testing
    TESTING=True
    DATABASE_URL=
    SECRET_KEY=test-secret-key
